#!/usr/bin/env python3
"""
Unified Draft Watcher — BCE-732

Scans GDrive drafts/{ECON,MAT,FOR}/ folders for new .md files and processes them
through the unified ingest_report.py pipeline.

Usage:
    python watch_drafts.py --type for               # FOR만 스캔+처리
    python watch_drafts.py --type all                # 전체 스캔+처리
    python watch_drafts.py --type econ --scan-only   # ECON 스캔만
    python watch_drafts.py --type all --dry-run      # 전체 테스트
"""

import argparse
import os
import subprocess
import sys
import threading
import queue
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pipeline_env import bootstrap_environment

bootstrap_environment()

os.environ.setdefault('GDRIVE_ROOT_FOLDER_ID', '')

REPORT_TYPES = ['econ', 'mat', 'for']
LOG_DIR = Path(__file__).resolve().parent.parent.parent / "logs" / "pipeline"
LOG_DIR.mkdir(parents=True, exist_ok=True)


def _log(message: str) -> None:
    timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    print(f"[{timestamp}] {message}", flush=True)


def scan_type(report_type: str, slug: str = None, force: bool = False) -> List[Dict]:
    from ingest_report import scan_drafts
    return scan_drafts(report_type, filter_slug=slug, force=force)


def process_type(report_type: str, dry_run: bool = False, slug: str = None, force: bool = False) -> tuple[int, int]:
    ingest_script = Path(__file__).parent / 'ingest_report.py'
    cmd = [sys.executable, str(ingest_script), '--type', report_type]
    if dry_run:
        cmd.append('--dry-run')
    if slug:
        cmd.extend(['--slug', slug])
    if force:
        cmd.append('--force')

    _log(
        "Executing: python ingest_report.py --type "
        f"{report_type}"
        f"{f' --slug {slug}' if slug else ''}"
        f"{' --force' if force else ''}"
        f"{' --dry-run' if dry_run else ''}"
    )

    try:
        proc = subprocess.Popen(
            cmd,
            cwd=ingest_script.parent,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert proc.stdout is not None

        output_queue: queue.Queue[str | None] = queue.Queue()
        captured_lines: list[str] = []

        def _reader() -> None:
            try:
                for line in proc.stdout:
                    output_queue.put(line)
            finally:
                output_queue.put(None)

        reader = threading.Thread(target=_reader, daemon=True)
        reader.start()

        start = time.monotonic()
        last_output = start
        heartbeat_seconds = 60
        timeout_seconds = 14400

        while True:
            now = time.monotonic()
            if now - start > timeout_seconds:
                proc.kill()
                raise subprocess.TimeoutExpired(cmd, timeout_seconds)

            try:
                item = output_queue.get(timeout=1)
            except queue.Empty:
                if now - last_output >= heartbeat_seconds:
                    elapsed = int(now - start)
                    _log(
                        f"{report_type.upper()} ingest still running "
                        f"({elapsed}s elapsed, {int(now - last_output)}s since last output)"
                    )
                    last_output = now
                if proc.poll() is not None and output_queue.empty():
                    break
                continue

            if item is None:
                if proc.poll() is not None:
                    break
                continue

            line = item.rstrip("\n")
            captured_lines.append(line)
            print(f"    {line}", flush=True)
            last_output = time.monotonic()

        returncode = proc.wait()
        stdout_text = "\n".join(captured_lines)
        published = stdout_text.count('published') if stdout_text else 0
        failed = stdout_text.count('[ERROR]') + stdout_text.count('[TERMINAL]') if stdout_text else 0

        if returncode != 0 and failed == 0:
            failed = 1

        return published, failed

    except subprocess.TimeoutExpired:
        _log("Pipeline timed out")
        return 0, 1
    except Exception as e:
        _log(f"Exception while running ingest subprocess: {e}")
        return 0, 1


def write_scan_log(scan_time: str, results: Dict[str, Dict]):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = LOG_DIR / f"pipeline_run_{timestamp}.md"

    lines = [
        "# Pipeline Draft Watcher Scan Log\n",
        f"**Scan Time:** {scan_time}\n",
    ]

    for rtype, data in results.items():
        lines.append(f"\n## {rtype.upper()}\n")
        lines.append(f"- New files: {data.get('new_files', 0)}")
        lines.append(f"- Published: {data.get('published', 0)}")
        lines.append(f"- Failed: {data.get('failed', 0)}\n")

    lines.append(f"\n---\n*Generated by BCE-732 Unified Draft Watcher*\n")
    log_file.write_text('\n'.join(lines))
    print(f"\n✓ Scan log: {log_file}")
    return str(log_file)


def main():
    parser = argparse.ArgumentParser(description='Unified Draft Watcher (BCE-732)')
    parser.add_argument('--type', required=True, help='Report type (econ, mat, for, all)')
    parser.add_argument('--scan-only', action='store_true', help='Scan only')
    parser.add_argument('--dry-run', action='store_true', help='Test mode')
    parser.add_argument('--slug', type=str, help='Process specific slug only')
    parser.add_argument('--force', action='store_true', help='Force re-process')
    args = parser.parse_args()

    types = REPORT_TYPES if args.type == 'all' else [args.type]
    scan_time = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    if not os.environ.get('GDRIVE_ROOT_FOLDER_ID'):
        print("ERROR: GDRIVE_ROOT_FOLDER_ID is required for draft scans.")
        return 1

    _log("=" * 60)
    _log("Pipeline Draft Watcher — BCE-732")
    _log(f"Types: {', '.join(t.upper() for t in types)}")
    _log(f"Scan Time: {scan_time}")
    _log("=" * 60)

    results = {}
    for rtype in types:
        _log(f"[SCAN] {rtype.upper()} drafts...")
        new_files = scan_type(rtype, slug=args.slug, force=args.force)
        _log(f"Found {len(new_files)} new file(s)")

        published, failed = 0, 0
        if new_files and not args.scan_only:
            published, failed = process_type(
                rtype,
                dry_run=args.dry_run,
                slug=args.slug,
                force=args.force,
            )

        results[rtype] = {
            'new_files': len(new_files),
            'published': published,
            'failed': failed,
        }

    log_file = write_scan_log(scan_time, results)

    _log("=" * 60)
    _log("SCAN COMPLETE")
    for rtype, data in results.items():
        _log(f"  {rtype.upper()}: {data['new_files']} new, {data['published']} published, {data['failed']} failed")
    _log("=" * 60)

    total_failed = sum(d['failed'] for d in results.values())
    return 1 if total_failed > 0 else 0


if __name__ == '__main__':
    sys.exit(main())
