#!/usr/bin/env python3
"""
Unified Draft Watcher — BCE-732

Scans GDrive drafts/{ECON,MAT,FOR}/ folders for new .md files and processes them
through the unified ingest_report.py pipeline.

Usage:
    python watch_drafts.py --type for               # FOR만 스캔+처리
    python watch_drafts.py --type all                # 전체 스캔+처리
    python watch_drafts.py --type econ --scan-only   # ECON 스캔만
    python watch_drafts.py --type all --dry-run      # 전체 테스트
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pipeline_env import bootstrap_environment

bootstrap_environment()

os.environ.setdefault('GDRIVE_ROOT_FOLDER_ID', '')

REPORT_TYPES = ['econ', 'mat', 'for']
LOG_DIR = Path(__file__).resolve().parent.parent.parent / "logs" / "pipeline"
LOG_DIR.mkdir(parents=True, exist_ok=True)


def scan_type(report_type: str, slug: str = None, force: bool = False) -> List[Dict]:
    from ingest_report import scan_drafts
    return scan_drafts(report_type, filter_slug=slug, force=force)


def process_type(report_type: str, dry_run: bool = False, slug: str = None, force: bool = False) -> tuple[int, int]:
    ingest_script = Path(__file__).parent / 'ingest_report.py'
    cmd = [sys.executable, str(ingest_script), '--type', report_type]
    if dry_run:
        cmd.append('--dry-run')
    if slug:
        cmd.extend(['--slug', slug])
    if force:
        cmd.append('--force')

    print(f"\n  Executing: python ingest_report.py --type {report_type}" +
          (f" --slug {slug}" if slug else "") +
          (" --force" if force else "") +
          (" --dry-run" if dry_run else ""))

    try:
        result = subprocess.run(
            cmd,
            cwd=ingest_script.parent,
            capture_output=True,
            text=True,
            timeout=14400,  # 4 hour timeout (batch processing)
        )
        if result.stdout:
            for line in result.stdout.splitlines():
                print(f"    {line}")

        # Count results from output
        published = result.stdout.count('published') if result.stdout else 0
        failed = result.stdout.count('[ERROR]') + result.stdout.count('[TERMINAL]') if result.stdout else 0

        if result.returncode != 0:
            if failed == 0:
                failed = 1
            if result.stderr:
                for line in result.stderr.splitlines()[-5:]:
                    print(f"    [ERR] {line}")

        return published, failed

    except subprocess.TimeoutExpired:
        print(f"    ✗ Pipeline timed out")
        return 0, 1
    except Exception as e:
        print(f"    ✗ Exception: {e}")
        return 0, 1


def write_scan_log(scan_time: str, results: Dict[str, Dict]):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = LOG_DIR / f"pipeline_run_{timestamp}.md"

    lines = [
        "# Pipeline Draft Watcher Scan Log\n",
        f"**Scan Time:** {scan_time}\n",
    ]

    for rtype, data in results.items():
        lines.append(f"\n## {rtype.upper()}\n")
        lines.append(f"- New files: {data.get('new_files', 0)}")
        lines.append(f"- Published: {data.get('published', 0)}")
        lines.append(f"- Failed: {data.get('failed', 0)}\n")

    lines.append(f"\n---\n*Generated by BCE-732 Unified Draft Watcher*\n")
    log_file.write_text('\n'.join(lines))
    print(f"\n✓ Scan log: {log_file}")
    return str(log_file)


def main():
    parser = argparse.ArgumentParser(description='Unified Draft Watcher (BCE-732)')
    parser.add_argument('--type', required=True, help='Report type (econ, mat, for, all)')
    parser.add_argument('--scan-only', action='store_true', help='Scan only')
    parser.add_argument('--dry-run', action='store_true', help='Test mode')
    parser.add_argument('--slug', type=str, help='Process specific slug only')
    parser.add_argument('--force', action='store_true', help='Force re-process')
    args = parser.parse_args()

    types = REPORT_TYPES if args.type == 'all' else [args.type]
    scan_time = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    if not os.environ.get('GDRIVE_ROOT_FOLDER_ID'):
        print("ERROR: GDRIVE_ROOT_FOLDER_ID is required for draft scans.")
        return 1

    print("=" * 60)
    print(f"Pipeline Draft Watcher — BCE-732")
    print(f"Types: {', '.join(t.upper() for t in types)}")
    print(f"Scan Time: {scan_time}")
    print("=" * 60)

    results = {}
    for rtype in types:
        print(f"\n[SCAN] {rtype.upper()} drafts...")
        new_files = scan_type(rtype, slug=args.slug, force=args.force)
        print(f"  Found {len(new_files)} new file(s)")

        published, failed = 0, 0
        if new_files and not args.scan_only:
            published, failed = process_type(
                rtype,
                dry_run=args.dry_run,
                slug=args.slug,
                force=args.force,
            )

        results[rtype] = {
            'new_files': len(new_files),
            'published': published,
            'failed': failed,
        }

    log_file = write_scan_log(scan_time, results)

    print("\n" + "=" * 60)
    print("SCAN COMPLETE")
    for rtype, data in results.items():
        print(f"  {rtype.upper()}: {data['new_files']} new, {data['published']} published, {data['failed']} failed")
    print("=" * 60)

    total_failed = sum(d['failed'] for d in results.values())
    return 1 if total_failed > 0 else 0


if __name__ == '__main__':
    sys.exit(main())
