"""
CRO Integration Module — Generates collector code for validated data sources
and integrates them into the report production pipeline.
"""
import os
import json
from typing import Dict, List, Optional
from datetime import datetime, timezone
from textwrap import dedent

from .source_registry import SourceRegistry

PIPELINE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COLLECTORS_DIR = os.path.join(PIPELINE_DIR, "collectors")
COLLECTOR_REGISTRY_PATH = os.path.join(COLLECTORS_DIR, "registry.json")


class PipelineIntegrator:
    """Integrates validated data sources into the pipeline."""

    # Template for generating a new collector module
    COLLECTOR_TEMPLATE = dedent('''\
    """
    BCE Lab Data Collector — {source_name}
    Auto-generated by CRO Agent on {generated_at}

    Category: {category}
    Base URL: {base_url}
    Auth: {auth_type}
    Rate Limit: {rate_limit_rpm} req/min
    Target Reports: {target_reports}
    """
    import time
    import requests
    from typing import Dict, List, Optional
    from datetime import datetime, timezone

    BASE_URL = "{base_url}"
    RATE_LIMIT_RPM = {rate_limit_rpm}
    AUTH_TYPE = "{auth_type}"
    SOURCE_NAME = "{source_name}"

    # Minimum interval between requests (seconds)
    MIN_INTERVAL = 60 / max(RATE_LIMIT_RPM, 1)

    _last_request_time = 0


    def _rate_limited_get(url: str, params: dict = None, headers: dict = None,
                          timeout: int = 15) -> Optional[requests.Response]:
        """Make a rate-limited GET request."""
        global _last_request_time
        elapsed = time.time() - _last_request_time
        if elapsed < MIN_INTERVAL:
            time.sleep(MIN_INTERVAL - elapsed)

        default_headers = {{"User-Agent": "BCE-Lab-Pipeline/1.0"}}
        if headers:
            default_headers.update(headers)

        try:
            resp = requests.get(url, params=params, headers=default_headers, timeout=timeout)
            _last_request_time = time.time()
            resp.raise_for_status()
            return resp
        except requests.RequestException as e:
            print(f"[{{SOURCE_NAME}}] Request error: {{e}}")
            return None


    def collect(token_id: str = None, symbol: str = None) -> Dict:
        """
        Collect data from {source_name}.

        Args:
            token_id: CoinGecko-style token ID (e.g., "bitcoin")
            symbol: Token symbol (e.g., "BTC")

        Returns:
            Dict with collected data, or empty dict on failure.
        """
        result = {{
            "source": SOURCE_NAME,
            "collected_at": datetime.now(timezone.utc).isoformat(),
            "data": {{}},
        }}

        try:
            # Primary data fetch
            resp = _rate_limited_get(BASE_URL)
            if resp:
                data = resp.json()
                result["data"] = data
                result["success"] = True
            else:
                result["success"] = False
                result["error"] = "No response"
        except Exception as e:
            result["success"] = False
            result["error"] = str(e)

        return result


    def health_check() -> Dict:
        """Check if the data source is reachable and returning valid data."""
        try:
            resp = _rate_limited_get(BASE_URL)
            if resp and resp.status_code == 200:
                data = resp.json()
                return {{
                    "status": "healthy",
                    "latency_ms": int(resp.elapsed.total_seconds() * 1000),
                    "data_present": bool(data),
                }}
        except Exception as e:
            return {{"status": "unhealthy", "error": str(e)}}
        return {{"status": "unhealthy", "error": "Unknown"}}
    ''')

    @classmethod
    def generate_collector(cls, source: Dict) -> str:
        """Generate a Python collector module for a validated source."""
        code = cls.COLLECTOR_TEMPLATE.format(
            source_name=source["source_name"],
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            category=source.get("category", "unknown"),
            base_url=source["base_url"],
            auth_type=source.get("auth_type", "none"),
            rate_limit_rpm=source.get("rate_limit_rpm", 30),
            target_reports=", ".join(source.get("target_report_types", [])),
        )
        return code

    @classmethod
    def save_collector(cls, source: Dict) -> str:
        """Generate and save a collector module for a source."""
        # Generate module name
        module_name = f"collector_{source['source_name'].lower().replace(' ', '_').replace('-', '_')}"
        file_path = os.path.join(COLLECTORS_DIR, f"{module_name}.py")

        # Generate code
        code = cls.generate_collector(source)

        # Ensure directory exists
        os.makedirs(COLLECTORS_DIR, exist_ok=True)

        # Write file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)

        print(f"  📝 Generated collector: {file_path}")
        return module_name

    @classmethod
    def update_collector_registry(cls, source: Dict, module_name: str) -> None:
        """Update the collector registry JSON with the new module."""
        registry = {}
        if os.path.exists(COLLECTOR_REGISTRY_PATH):
            with open(COLLECTOR_REGISTRY_PATH, "r") as f:
                registry = json.load(f)

        registry[source["source_name"]] = {
            "module": module_name,
            "category": source.get("category"),
            "base_url": source["base_url"],
            "auth_type": source.get("auth_type", "none"),
            "target_report_types": source.get("target_report_types", []),
            "integrated_at": datetime.now(timezone.utc).isoformat(),
            "quality_scores": {
                "reliability": source.get("reliability_score", 0),
                "freshness": source.get("freshness_score", 0),
                "coverage": source.get("coverage_score", 0),
                "quality": source.get("quality_score", 0),
                "overall": source.get("overall_score", 0),
            },
        }

        with open(COLLECTOR_REGISTRY_PATH, "w") as f:
            json.dump(registry, f, indent=2, ensure_ascii=False)

        print(f"  📋 Updated collector registry")

    @classmethod
    def integrate_source(cls, source: Dict) -> Dict:
        """
        Full integration: generate collector, update registry, update Supabase.
        Only works for 'validated' sources.
        """
        source_id = source.get("id")
        source_name = source.get("source_name", "Unknown")

        if source.get("status") != "validated":
            return {
                "success": False,
                "error": f"Source '{source_name}' is not validated (status={source.get('status')})",
            }

        print(f"\n🔗 Integrating: {source_name}")

        # 1. Generate collector module
        module_name = cls.save_collector(source)

        # 2. Update collector registry
        cls.update_collector_registry(source, module_name)

        # 3. Update Supabase status
        if source_id:
            SourceRegistry.update_source(source_id, {
                "status": "integrated",
                "collector_module": module_name,
            })
            SourceRegistry.log_improvement(
                action_type="source_integrated",
                source_id=source_id,
                description=f"Integrated {source_name} as {module_name}",
                impact=f"New data available for reports: {source.get('target_report_types', [])}",
            )

        return {
            "success": True,
            "source_name": source_name,
            "module_name": module_name,
            "target_reports": source.get("target_report_types", []),
        }

    @classmethod
    def integrate_all_validated(cls) -> List[Dict]:
        """Integrate all validated sources that haven't been integrated yet."""
        validated = SourceRegistry.get_validated_sources()
        print(f"Found {len(validated)} validated sources to integrate\n")

        results = []
        for source in validated:
            try:
                result = cls.integrate_source(source)
                results.append(result)
            except Exception as e:
                print(f"  ❌ Error integrating {source.get('source_name')}: {e}")
                results.append({
                    "success": False,
                    "source_name": source.get("source_name"),
                    "error": str(e),
                })

        integrated = [r for r in results if r.get("success")]
        print(f"\n📋 Integration Summary: {len(integrated)}/{len(results)} successful")
        return results

    @classmethod
    def get_integration_status(cls) -> Dict:
        """Get current integration status summary."""
        all_sources = SourceRegistry.get_all_sources()

        status_counts = {}
        for s in all_sources:
            st = s.get("status", "unknown")
            status_counts[st] = status_counts.get(st, 0) + 1

        integrated = [s for s in all_sources if s.get("status") == "integrated"]
        categories_covered = set(s.get("category") for s in integrated)

        return {
            "total_sources": len(all_sources),
            "status_distribution": status_counts,
            "integrated_count": len(integrated),
            "categories_covered": sorted(categories_covered),
            "missing_categories": sorted(
                {"derivatives", "social", "governance", "regulatory", "news"}
                - categories_covered
            ),
        }
