-- BCE-1893 follow-up: MAT reports that have valid slide assets must not stay
-- hidden behind the retired in_review state.
--
-- The public Top 200 page only exposes published report rows. These rows were
-- generated by the MAT pipeline and have report assets, but remained in_review
-- after ingestion. Publish them so the scoreboard and project pages stay aligned
-- with Google Drive slide availability.

UPDATE project_reports
SET
  status = 'published',
  published_at = COALESCE(published_at, NOW()),
  updated_at = NOW()
WHERE report_type = 'maturity'
  AND status = 'in_review'
  AND (
    NULLIF(BTRIM(gdrive_url), '') IS NOT NULL
    OR NULLIF(BTRIM(file_url), '') IS NOT NULL
    OR COALESCE(gdrive_urls_by_lang, '{}'::jsonb) <> '{}'::jsonb
    OR COALESCE(file_urls_by_lang, '{}'::jsonb) <> '{}'::jsonb
    OR COALESCE(slide_html_urls_by_lang, '{}'::jsonb) <> '{}'::jsonb
  )
  AND EXISTS (
    SELECT 1
    FROM tracked_projects
    WHERE tracked_projects.id = project_reports.project_id
      AND tracked_projects.status IN ('active', 'monitoring_only')
  );
